name=OtaHub
version=1.0.0
author=Chamara Gayan <support@otahub.dev>
maintainer=Chamara Gayan <support@otahub.dev>
sentence=Official Arduino library for OtaHub.dev - The ESP32 OTA Firmware Distribution Platform
paragraph=Scale your IoT fleet with OtaHub. Securely host, tag, and distribute firmware updates over-the-air to ESP32 devices via a simple REST API.
category=Device Control
url=https://otahub.dev
architectures=esp32
includes=otahub.h
